from pathlib import Path

from tianwai import create_app
from tianwai.db import _postgres_sql, database_backend


def test_database_backend_defaults_to_sqlite(monkeypatch):
    monkeypatch.delenv("DATABASE_URL", raising=False)
    assert database_backend() == "sqlite"


def test_database_backend_selects_postgres(monkeypatch):
    monkeypatch.setenv("DATABASE_URL", "postgresql://example.invalid/app")
    assert database_backend() == "postgresql"


def test_postgres_sql_converts_qmark_parameters():
    query = "SELECT * FROM orders WHERE order_no = ? AND status = ?"
    assert _postgres_sql(query) == (
        "SELECT * FROM orders WHERE order_no = %s AND status = %s"
    )


def test_postgres_sql_converts_insert_or_ignore():
    query = """
        INSERT OR IGNORE INTO settings (key, value, updated_at)
        VALUES (?, ?, ?)
    """
    converted = _postgres_sql(query)
    assert "INSERT INTO settings" in converted
    assert "INSERT OR IGNORE" not in converted
    assert converted.rstrip().endswith("ON CONFLICT DO NOTHING")
    assert converted.count("%s") == 3


def test_postgres_schema_has_no_sqlite_only_statements():
    schema = (
        Path(__file__).resolve().parents[1] / "tianwai" / "schema_postgres.sql"
    ).read_text(encoding="utf-8")
    assert "PRAGMA" not in schema
    assert "AUTOINCREMENT" not in schema
    assert "GENERATED BY DEFAULT AS IDENTITY" in schema
    assert "admin_sessions" in schema
    assert "notification_queue" in schema


def test_sqlite_health_response_does_not_expose_database_location(tmp_path):
    database_path = tmp_path / "backend.db"
    app = create_app(
        {
            "TESTING": True,
            "DATABASE": str(database_path),
            "SECRET_KEY": "test-secret",
        }
    )
    response = app.test_client().get("/healthz")
    body = response.get_json()
    assert response.status_code == 200
    assert body["status"] == "ok"
    assert str(database_path) not in response.get_data(as_text=True)
    assert "postgresql://" not in response.get_data(as_text=True)
